[package]
name = "check_commit_msg"
version = "0.1.0"
authors = ["Dillon Sahadevan <dillon.sahadevan@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
